// PRODUCT
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"

// CART
export const ADD_PRODUCT_CART = "ADD_PRODUCT"
export const CHANGE_PRODUCT_QUANTITY_CART = "CHANGE_PRODUCT_QUANTITY"
export const REMOVE_PRODUCT_CART = "REMOVE_PRODUCT"
